Claims/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',


	url(r'^$', 'Claims.views.index'),
	url(r'^login/$' , 'django.contrib.auth.views.login',
		{'template_name':'login.html'}, name='login'),
	url(r'^logged_in/$', 'Claims.views.logged_in'),
	url(r'^detalles/(?P<id>\d+)/$', 'Claims.views.detalle'),
	url(r'^claims/$', 'Claims.views.claims'),
	url(r'^historial/$', 'Claims.views.historial'),
	url(r'^cerrar/$' , 'django.contrib.auth.views.logout',
						{'next_page': 'Claims.views.index'})
)

app/urls.py
from django.conf.urls import patterns, url
from .views import *


urlpatterns = patterns('',
    url(r'^token$', apptoken, name='apptoken'),
    url(r'^validate', validate_token , name='validate_token'),
    url(r'^(?P<app_id>\d+)/$', AppHomeView.as_view(), name='apphome'),
    url(r'^(?P<app_id>\d+)/admins$', AppHomeView.as_view(), name='appadmins'),
    url(r'^(?P<app_id>\d+)/key$', AppResetKeyView.as_view(), name='resetkey'),
    url(r'^$', select_app, name='select'),
)

claims/urls.py
from django.conf.urls import patterns, url
from claims import views

urlpatterns = patterns('',
    url(r'^/(?P<rfc>\w+)/eventos$', views.EventosView.as_view(), name='eventos'),
    url(r'^/(?P<rfc>\w+)/eventos/$', views.EventosView.as_view(), name='eventos'),
    url(r'^/(?P<rfc>\w+)$', views.ProveedoresView.as_view(), name='proveedor'),
    url(r'^/(?P<rfc>\w+)/$', views.ProveedoresView.as_view(), name='proveedor'),
    url(r'^/(?P<rfc>\w+)/eventos/(?P<evento_id>\d+)$', views.EventoDetailView.as_view(), name='evento')
)

ecsclaims/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework.urlpatterns import format_suffix_patterns

from claims import urls as claims_urls
from app import urls as app_urls
from claims.views import routes, login
from app.views import apptoken, AppResetKeyView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('settings.urls')),
    url(r'^', include('claims_Web.urls')),
    url(r'^proveedores', include('claims.urls')),
    url(r'^apps/', include("app.urls")),
    url(r'^auth/login$', login, name='login'),
    url(r'^', include('django.contrib.auth.urls')),
    #url(r'^api-token-auth/', 'rest_framework_jwt.views.obtain_jwt_token'),
    url(r'^routes/', routes, name='routes'),
    url(r'^', include('invoices_Web.urls')),
    url(r'^explorer/', include('explorer.urls')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

Claims/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Paciente(models.Model):
   Nombre = models.CharField(max_length=255, null=False)
   CURP = models.CharField(max_length=18, null=False)
   FichaEmpleado = models.CharField(max_length=255, null=False)
   NumeroEmpresa = models.CharField(max_length=255, null=False)
   PesoEstatura = models.CharField(max_length=255, null=False)
   FechaNacimiento = models.DateField()
   Sexo = models.CharField(max_length=255, null=False)

class Medico(models.Model):
   Nombre = models.CharField(max_length=255, null=False)
   Especialidad = models.CharField(max_length=255, null=False)
   Cedula = models.CharField(max_length=255, null=False)
   RFC = models.CharField(max_length=13, null=False)

class Proveedor(models.Model):
   RFC = models.CharField(max_length=13, null=False)
   Cliente = models.CharField(max_length=255, null=False)
   Organizacion = models.CharField(max_length=255, null=False)
   Localidad = models.CharField(max_length=255, null=False)

class Cuenta(models.Model):
   IdPaciente = models.ForeignKey(Paciente)
   IdMedico = models.ForeignKey(Medico)
   IdProveedor = models.ForeignKey(Proveedor)
   Diagnostico = models.CharField(max_length=255, null=False)
   FechaAdmision = models.DateTimeField()
   FechaAlta = models.DateTimeField()

class Cargo(models.Model):
   IdCuenta = models.ForeignKey(Cuenta)
   Descripcion = models.CharField(max_length=255, null=False)
   UnidadDeMedida = models.CharField(max_length=255, null=False)
   Cantidad = models.IntegerField(null=False)
   PrecioUnitario = models.DecimalField(max_digits=10, decimal_places=2)
   Descuento = models.DecimalField(max_digits=10, decimal_places=2)
   PrecioNeto = models.DecimalField(max_digits=10, decimal_places=2)
   Impuesto = models.DecimalField(max_digits=10, decimal_places=2)
   FechaAplicacion = models.DateTimeField()

class Autorizacion(models.Model):
   Folio = models.CharField(max_length=255, null=False)
   IdCuenta = models.ForeignKey(Cuenta)
   Estatus = models.CharField(max_length=255, null=False)
   FechaSolicitud = models.DateField()
   Comentarios  = models.CharField(max_length=255)
   TipoAprobacion = models.CharField(max_length=255)
   Sistema = models.CharField(max_length=255, null=False)

claims/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from invoices_Web.models import Comprobante
import datetime
from django.conf import settings
from django.core.validators import RegexValidator

# Create your models here.

x = datetime.datetime.now()

EVENT_TIPO = (
('C', 'Cita'),
('A', 'Ambulatorio'),
('H', 'Hospitalizacion'),
('U', 'Urgencia'),
)

MEDICO_TIPO = (
('PC','Familiar'),
('RP','Referencia'),
('AP','Admision'),
('TP','Atencion'),
('CP','Consultor'),
('CO','Cobertura'),
('AS','Asistente'),
('AN','Anesteciologo'),
('IN','Interprete'),
('ER','Urgenciologo'),
('PP','Cirujano'),
)

YES_NO = (
('Y', 'Si'),
('N', 'No'),
)

EVENT_ESTATUS = (
('A', 'Abierto'),
('C', 'Cerrado'),
)

DX_ESTATUS = (
('A', 'Activo'),
('I', 'Inactivo'),
('R', 'Resuelto'),
)

AUTH_ESTATUS =(
('R', 'Recibido'),
('V', 'Validado PEMEX'),
('A', 'Aceptado PEMEX'),
('X', 'Rechazado PEMEX'),
('Y', 'Aceptado MAC'),
('N', 'Rechazado MAC'),
('E', 'En Revision MAC'),
('P', 'En Revision PEMEX'),
)


class Motivos(models.Model):
   motivo = models.CharField(max_length=255, null=False)
   is_active = models.CharField(null=False,max_length=1,choices= YES_NO)

class Localidad(models.Model):
   codigo = models.CharField(max_length=255, null=False)
   nombre = models.CharField(max_length=255, null=False)
   def __str__(self):
      return "%s" % (self.nombre)

class Proveedor(models.Model):
   phone_regex = RegexValidator(regex=r'^\+?1?\d{13}$', message="Numero debe ingresarse en formato internacional: '+521999999'. 14 digitos en total.")
   owner = models.OneToOneField(User, null=True)
   rfc = models.CharField(max_length=13, null=False)
   cliente = models.CharField(max_length=255, null=False)
   org = models.CharField(max_length=255, null=False)
   hospital=models.CharField(max_length=255, null=False)
   localidad=models.CharField(max_length=255, null=False)
   email = models.EmailField(max_length=70,blank=True)
   celular = models.CharField(max_length=14, validators=[phone_regex], blank=True) 
   whatsapp = models.CharField(choices= YES_NO,max_length=1,default='N')
   telegram = models.CharField(choices= YES_NO,max_length=1,default='N')
   sms = models.CharField(choices= YES_NO,max_length=1,default='N')
   tgcontacto = models.CharField(max_length=255, blank=True)
   def __str__(self):
      return "%s - %s" % (self.rfc, self.localidad)

class TipoUsuario(models.Model):
   MACSUPERVISOR = 'S'
   MACCOORDINADOR = 'C'
   MACNACIONAL = 'N'
   MAC = 'M'
   PEMEX = 'P'
   PEMEXAUXILIAR = 'A'
   PEMEXSUPERVISOR = 'S'
   PEMEXCOORDINADOR = 'C'
   PEMEXNACIONAL = 'N'
   ECARESOFT = 'E'
   SUPERUSER = 'S'
   MAC_USER = (
      (MACSUPERVISOR,'SUPERVISOR'),
      (MACCOORDINADOR,'COORDINADOR'),
      (MACNACIONAL,'COORDINADOR NACIONAL'),
   )
   PEMEX_USER = (
      (PEMEXAUXILIAR,' AUXILIAR'),
      (PEMEXSUPERVISOR,' SUPERVISOR MEDICO SECTORIAL'),
      (PEMEXCOORDINADOR,' COORDINADOR ZONA'),
      (PEMEXNACIONAL,' COORDINADOR NACIONAL'),
   )
   TIPO_USER = (
      (MAC,'MAC'),
      (PEMEX,'PEMEX'),
      (ECARESOFT,'ECARESOFT'),
      (SUPERUSER,'SUPER USER'),
   )
   user = models.ForeignKey(User)
   tipo = models.CharField(choices=TIPO_USER,max_length=1)
   subtipo = models.CharField(null=True,max_length=1,default='Q')
   phone_regex = RegexValidator(regex=r'^\+?1?\d{13}$', message="Numero debe ingresarse en formato internacional: '+521999999'. 14 digitos en total.")
   email = models.EmailField(max_length=70,blank=True)
   celular = models.CharField(max_length=14, validators=[phone_regex], blank=True) 
   whatsapp = models.CharField(choices= YES_NO,max_length=1,default='N')
   telegram = models.CharField(choices= YES_NO,max_length=1,default='N')
   sms = models.CharField(choices= YES_NO,max_length=1,default='N')
   tgcontacto = models.CharField(max_length=255, blank=True)
   def __str__(self):
      return "%s" % (self.user.username)


class UsuarioLocalidad(models.Model):
   usuario = models.ForeignKey(User)
   localidad = models.ForeignKey(Localidad)
   def __str__(self):
      return "%s" % (self.usuario.username)

class Evento(models.Model):
   folioAut = models.CharField(max_length=255)
   numEvento = models.CharField(max_length=255)
   fechaAdm = models.DateTimeField()
   fechaAlta = models.DateTimeField()
   fechaPrimerCargo = models.DateTimeField(null=True)
   cedula = models.CharField(max_length=50)
   nommedico = models.CharField(max_length=255)
   tipo = models.CharField(choices=EVENT_TIPO, max_length=1)
   tipoFolio = models.CharField(max_length=255,null=True)
   estatus = models.CharField(choices= EVENT_ESTATUS, max_length=1)
   proveedor = models.ForeignKey(Proveedor)
   total = models.DecimalField(max_digits=12, decimal_places=2)
   eventoIdCumulus = models.CharField(max_length=255,null=True,default=0)
   
class Paciente(models.Model):
   curp = models.CharField(max_length=18, null=False)
   fichaEmp = models.CharField(max_length=12, null=False)
   numCod = models.CharField(max_length=2, null=False)
   numEmpresa = models.CharField(max_length=6, null=False)
   nombre = models.CharField(max_length=255, null=False)
   folioVigencia = models.CharField(max_length=255, null=False)
   evento = models.ForeignKey(Evento)

class Medico(models.Model):
   secuencia = models.PositiveSmallIntegerField()
   tipo = models.CharField(choices= MEDICO_TIPO, max_length=2)
   nombre = models.CharField(max_length=255)
   especialidad = models.CharField(max_length=255)
   cedula = models.CharField(max_length=255)
   evento = models.ForeignKey(Evento)

class Procedimiento(models.Model):
   secuencia = models.PositiveSmallIntegerField()
   sistema = models.CharField(max_length=255)
   codigo = models.CharField(max_length=255)
   nombre = models.CharField(max_length=255)
   fecha = models.DateField()
   observaciones = models.CharField(max_length=255,null=True)
   medico = models.ForeignKey(Medico)
   evento = models.ForeignKey(Evento)

class Dx(models.Model):

   secuencia = models.PositiveSmallIntegerField()
   sistema = models.CharField(max_length=255)
   codigo = models.CharField(max_length=255)
   nombre = models.CharField(max_length=255)
   estatus = models.CharField(choices= DX_ESTATUS, max_length=1)
   admision = models.CharField(choices= YES_NO,max_length=1,default='N')
   fecha = models.DateTimeField()
   observaciones = models.CharField(max_length=255,null=True)
   medico = models.ForeignKey(Medico,null=True)
   evento = models.ForeignKey(Evento)

class Cargo(models.Model):
   evento = models.ForeignKey(Evento)
   secuencia = models.PositiveSmallIntegerField()
   fechaApli = models.DateTimeField()
   codigo = models.CharField(max_length=255)
   descripcion = models.CharField(max_length=255)
   udm = models.CharField(max_length=255)
   sistema = models.CharField(max_length=255)
   sistemaCodigo = models.CharField(max_length=255)
   cantidad = models.PositiveSmallIntegerField()
   precio = models.DecimalField(max_digits=12, decimal_places=2)
   subtotal = models.DecimalField(max_digits=12, decimal_places=2)
   iva = models.DecimalField(max_digits=12, decimal_places=2)
   descuento = models.DecimalField(max_digits=12, decimal_places=2)
   total = models.DecimalField(max_digits=12, decimal_places=2)


class CargosDx(models.Model):
   dx = models.ForeignKey(Dx)
   cargo = models.ForeignKey(Cargo)

class Autorizacion(models.Model):
   estatus = models.CharField(choices= AUTH_ESTATUS, max_length=255, null=False)
   fechaSolicitud = models.DateField()
   comentarios  = models.CharField(max_length=255,null=True)
   tipoAprobacion = models.CharField(max_length=255)
   sistema = models.CharField(max_length=255, null=False)
   evento = models.ForeignKey(Evento,null=True)
   comprobante = models.ForeignKey(Comprobante,null=True)
   motivo = models.ForeignKey(Motivos, blank=True, null=True)

Claims/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from Claims.models import *
import datetime

def index(request):
    return render_to_response('index.html',
        context_instance=RequestContext(request)
    )


@login_required
def logged_in(request):
	nombre = request.user.get_full_name()
	return render_to_response('pantallas.html',RequestContext(request,locals()))

@login_required
def detalle(request, id):
	idd=id
	bandera=0
	if request.POST:
		estatus = request.POST.get('estatus')
		descripcion = request.POST.get('descripcion')
		Autorizacion.objects.filter(id=idd).update(Estatus=estatus,Comentarios=descripcion)
		bandera=1
		nombre = request.user.get_full_name()
		autorizacion = Autorizacion.objects.all().filter(Estatus='Recibido',TipoAprobacion='1')
		cuenta = Cuenta.objects.all()
		paciente = Paciente.objects.all()
		proveedor = Proveedor.objects.all()
		cargo = Cargo.objects.all()
		return render_to_response('claims/claims.html',RequestContext(request,locals()))
	nombre = request.user.get_full_name()
	detalle = get_object_or_404(Cuenta, id=id)
	paciente = Paciente.objects.all()
	medico = Medico.objects.all()
	cargo = Cargo.objects.all()
	return render_to_response('claims/detalles.html',RequestContext(request,locals()))

@login_required
def claims(request):
	x = datetime.datetime.now()
	inicio = "%s-%s-%s"% (x.year, x.month, x.day)
	fin = "%s-%s-%s"% (x.year, x.month, x.day)
	nombre = request.user.get_full_name()
	autorizacion = Autorizacion.objects.all().filter(Estatus='Recibido',TipoAprobacion='1')
	cuenta = Cuenta.objects.all()
	paciente = Paciente.objects.all()
	proveedor = Proveedor.objects.all()
	cargo = Cargo.objects.all()
	if request.POST:
		autorizacion = Autorizacion.objects.all().filter(Estatus='Recibido',TipoAprobacion='1',FechaSolicitud__range=[request.POST.get("inicio"), request.POST.get("fin")])
		if request.POST.get("tipo") != 'vacio':
			autorizacion = Autorizacion.objects.all().filter(Sistema=request.POST.get("tipo"),TipoAprobacion='1')
		if request.POST.get("cliente") != 'vacio':
			cuenta = Cuenta.objects.all().filter(IdProveedor_id=request.POST.get("cliente"))
		inicio = request.POST.get("inicio")
		fin = request.POST.get("fin")

    	return render_to_response('claims/claims.html',RequestContext(request,locals()))

@login_required
def historial(request):
	nombre = request.user.get_full_name()
	autorizacion = Autorizacion.objects.all().filter(TipoAprobacion='1')
	cuenta = Cuenta.objects.all()
	paciente = Paciente.objects.all()
	proveedor = Proveedor.objects.all()
	cargo = Cargo.objects.all()
    	return render_to_response('claims/historial.html',RequestContext(request,locals()))

templates/claims/claims.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
  eCS Claims
{% endblock title %}

{% block css %}
  <link type="text/css" href="{% static "css/pnotify.css" %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
  <style type="text/css">
    #footer {
        padding: 4em 0 6em 0;
        text-align: center;
    }
    #footer .copyright {
        color: #999;
        font-size: 0.9em;
        line-height: 1em;
        margin: 2em 0 0 0;
        padding: 0;
        text-align: center;
    }
    #footer .copyright li {
        display: inline-block;
        list-style: none;
        margin-left: 1em;
        padding-left: 1em;
    }
  </style>
{% endblock css %}

{% block header %}
  <div id="jCrumbs" class="breadCrumb module">
    <ul>
      <li>
        <a href="/logged_in/"><i class="glyphicon glyphicon-home"></i></a>
      </li>
      <li>
        <a href="">Estado de cuenta</a>
      </li>
      <li>
        <a href="">Pendientes</a>
      </li>
    </ul>
  </div>
  <div class="row">
    <div class="12u">
      <section class="box">
        <center><h3>Estado de cuenta Pendientes</h3></center>
        <hr />
        <form action="" class="form-horizontal" method="POST">{% csrf_token %}
          <button style="margin-left:95%;margin-bottom:20px;" type="submit"><i class="fa fa-refresh"></i></button>
          <div class="form-group">
              <label class="col-md-3 control-label">Rango de Fechas</label>
              <div class="col-xs-4">
                <div class="input-icon">
                  <input type="text" name="daterange" class="input-error form-control" value="{{start}}-{{end}}" />
                </div>
              </div>
          </div>
        </form>
        <hr />
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="tabletools">
          <thead>
            <tr>
              <th>Fecha</th>
              <th>Localidad</th>
              <th>Hospital</th>
              <th>Paciente</th>
              <th>Folio</th>
              <th>Total</th>
              <th>Detalle</th>
            </tr>
          </thead>
          <tbody id="tb">
            {% for auths in auth %}
              <tr>
                {% for events in event %}
                  {% if auths.evento_id == events.id %}
                    <td>{{auths.fechaSolicitud}}</td>
                    {% for providers in provider %}
                      {% if providers.id == events.proveedor_id %}
                        <td>{{providers.localidad}}</td>
                        <td>{{providers.hospital}}</td>
                      {% endif %}
                    {% endfor %}                            
                    {% for patients in patient %}
                      {% if patients.evento_id == events.id %}
                        <td>{{patients.nombre}}</td>
                      {% endif %}
                    {% endfor %}
                    <td>{{events.folioAut}}</td>
                    <td>{{events.total}}</td>
                    <th>
                      <a style="margin-left:0 !important;" class="a-details" href="{{ settings.APP_URL }}/detalles/{{auths.evento_id}}/">
                        <i class="fa fa-eye"></i>
                      </a>
                    </th>
                  {% endif %}
              {% endfor %}  
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </section>
    </div>
  </div>
{% endblock header %}
{% block javascript %}
  <script type="text/javascript" src="{% static "js/pnotify.min.js" %}"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      console.log('{{bug}}');
      $('input[name="daterange"]').daterangepicker(
        {
            locale: {
              format: 'YYYY-MM-DD',
              closeText: 'Cerrar',
              prevText: '<Ant',
              nextText: 'Sig>',
              currentText: 'Hoy',
              monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
              monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
              dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
              dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
              dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
              weekHeader: 'Sm',
              firstDay: 1,
              isRTL: false,
              showMonthAfterYear: false,
              yearSuffix: ''
            },
            startDate: '{{start}}',
            endDate: '{{end}}'
        });
      $('.applyBtn').css('display','none');
      $('.cancelBtn').css('display','none');
    });
  </script>
  {% if success == 1 %}
    <script>
      $(document).ready(function(){
        new PNotify({
                title: 'Exito',
                text: 'El reclamo seleccionado se actualizo con exito!',
                type: 'success',
                styling: 'fontawesome'
              });
      });
    </script>
  {% endif %}
  {% if error == 1 %}
    <script>
      $(document).ready(function(){
        new PNotify({
                title: 'Error',
                text: 'No se envio notificación a los usuarios!',
                type: 'error',
                styling: 'fontawesome'
              });
      });
    </script>
  {% endif %}
{% endblock javascript %}

templates/claims/historial.html
{% extends 'base.html' %}

{% block title %}
  eCS Claims
{% endblock title %}

{% block css %}
  <style type="text/css">
    #footer {
        padding: 4em 0 6em 0;
        text-align: center;
    }
    #footer .copyright {
        color: #999;
        font-size: 0.9em;
        line-height: 1em;
        margin: 2em 0 0 0;
        padding: 0;
        text-align: center;
    }
    #footer .copyright li {
        display: inline-block;
        list-style: none;
        margin-left: 1em;
        padding-left: 1em;
    }
    .a-details,.a-details:hover{
      font-size: 30px;
      margin-left: 80%;
      border: none !important;
    }
  </style>
{% endblock css %}

{% block header %}
  <div id="jCrumbs" class="breadCrumb module">
    <ul>
      <li>
        <a href="/logged_in/"><i class="glyphicon glyphicon-home"></i></a>
      </li>
      <li>
        <a href="">Estado de cuenta</a>
    </li>
    <li>
        <a href="">Historial</a>
    </li>
    </ul>
  </div>
  <div class="row">
    <div class="12u">
      <section class="box">
        <center><h3>Lista de Estado de cuenta</h3></center>
        <hr />
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="tabletools">
            <thead>
              <tr>
                <th>Fecha</th>
                <th>Localidad</th>
                <th>Hospital</th>
                <th>Estatus</th>
                <th>Folio</th>
                <th>Total</th>
                <th>Detalle</th>
              </tr>
            </thead>
            <tbody id="tb">
              {% for auths in auth %}
                  <tr>
                    {% for events in event %}
                      {% if events.id == auths.evento_id %}
                        <td>{{auths.fechaSolicitud}}</td>
                        {% for providers in provider %}
                          {% if providers.id == events.proveedor_id %}
                            <td>{{providers.localidad}}</td>
                            <td>{{providers.hospital}}</td>
                          {% endif %}
                        {% endfor %}                            
                        <td>{{auths.get_estatus_display}}</td>
                        <td>{{events.folioAut}}</td>
                        <td>{{events.total}}</td>
                        <th>
                          <a style="margin-left:0 !important;" href="{{ settings.APP_URL }}/historial_detalles/{{auths.evento_id}}/">
                            <i class="fa fa-eye"></i>
                          </a>
                        </th>
                      {% endif %}
                    {% endfor %}
                  </tr>
              {% endfor %}
            </tbody>
          </table>
      </section>
    </div>
  </div>
{% endblock header %}

templates/claims/motivolistado.html
{% extends "base.html" %}
  {% block content %}
  <h2>Motivos</h2>
  <em>Motivo - Nombre</em>
  <ul>
    {% for motivo in object_list %}
      <li>{{ motivo.nombre }} </li>
    {% endfor %}
  </ul>
  {% endblock %}